### ISSUE TITLE
Infinite Fluid Bug

### ISSUE THREAD

**Issue by NekoGoken** [Kinetic-Development/Mythic#2]
So I was busy filling a Resonant fluid transposer with gelid cryotheum, and I realized, if you put a empty bucket in the fluid transposer and set it to fill, It gives you rapid amounts of a random liquid, sometimes even a stack of infinite water buckets. I don't know why but That is the exact process i used.
Power a fluid transposer resonant
Send it to fill
Put empty buckets in it
Some bullshit happens.
IGN: Neko_Goken

**Comment by SleepingTea98** [comment]
This is a dupe bug with the mod, we'll look into it, but there might not be anything we can do.

Thanks for the report
